### ISSUE TITLE
Unable to Clone or Copy the Power BI Report

### ISSUE THREAD

**Issue by sammicrosoft** [Microsoft/PowerBI-Developer-Samples#27]
Dear All,
 
I had written the below code to clone the Power BI report , But I don't find the luck to clone the report .
Can any one help me in knowing what's wrong or any parameter missing in my below code.
 
`
function CopyReport(reportId, Name, Dataset) {
    debugger;
    var deferred = $.ajax({
        url: "https://api.powerbi.com/v1.0/myorg/reports/" + reportId + "/Clone",
        type: "POST",
        headers: {
            "Authorization": "Bearer " + accessToken
        },
       // ContentType: "application/json",
        data: { Name: Name},
        //data: { name: Name, targetWorkspaceId: Dataset },
        success: function (responseData) {
            cache.write(responseData, "Copy report")
        },
        error: function (responseData) {
            debugger;
            cache.write(responseData, "Copy report")
        }
    });
    return deferred.promise();
}

`
****Error**:** : 
{"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}

**Comment by ali-hamud** [comment]
The body of the request is not correct. correct body should include:
{
  "name": "string",
  "targetWorkspaceId": "string",
  "targetModelId": "string"
}

if you are cloning the report to the same workspace, then only "name" is required.
otherwise, you should give:
targetWorkspaceId - which workspace (group) you want to copy the report to.
targetModelId - which dataset in the new workspace you want to bind the report with.

Thanks,
Ali Hamud

**Comment by sammicrosoft** [comment]
Hamud,

We are using in same workspace
