### ISSUE TITLE
After integrated into the web, you also need to log in once, why?

### ISSUE THREAD

**Issue by yeacer** [Microsoft/PowerBI-Developer-Samples#39]
Hello, integrated into the web, but also need to log in once, and why? Looking forward to your reply Thank you

**Comment by ali-hamud** [comment]
Hi,
Which example did you use (AppOwnsData or UserOwnsData)?

Think about it this way, if your application users owns Power BI reports, you will need them to sign in with their accounts in order to access their reports.
If you own Power BI Reports, and you want to share them with Embed Tokens, you will need to use AppOwnsData sample (for this you need to register native AAD application).

**Comment by yeacer** [comment]
We use UserOwnsData now, because we used AppOwnsData error, the error message is as follows
![_20180115174812](https://user-images.githubusercontent.com/35021799/34936423-488a6284-fa1c-11e7-885e-188c73cc27b8.png)

**Comment by yeacer** [comment]
@ali-hamud We use UserOwnsData now, because we used AppOwnsData error, the error message is as follows  
![_20180115174812](https://user-images.githubusercontent.com/35021799/34937041-5595cbd8-fa1e-11e7-97fc-53a2d1984c21.png)

**Comment by zxy7** [comment]
@yeacer  Have you solved?  How？i meet the same question with u.
i use AppOwnsData  because  i don't want to  enter the username and password to log in  power bi every time  like  UserOwnsData . @ali-hamud
